import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main >
        <div>
          <img src="/hero.jpg" alt="" className='object-cover  object-centerw-screen ' style={{width : "100vw", height :"75vh"}}/>
        </div>
      </main>
      <Footer/>
    </>
  )
}
